development:
  adapter: postgresql
  encoding: unicode
  database: akshara
  host: localhost
  pool: 5
  username: afzal
  password: afzal

development:
  adapter: postgresql
  encoding: unicode
  database: akshara_rails
  host: localhost
  pool: 5
  username: akshara
  password: akshara
